### ISSUE TITLE
News Exception 

### ISSUE THREAD

**Issue by beihrle** [madskristensen/DeveloperNews#9] opened 2020-07-06 22:29 UTC
I followed these steps. Note I do not have the independent "Developer news" extension.
Installed "Developer news" extension. 
Started VS with Exception.
uninstalled "Developer news" extension. 
installed the Basic Essentials extension.
Installed "Developer news" extension again.
Started up VS and still greeted with exception on blank tab.

Construction of frame content failed.&#x000D;&#x000A;Frame identifier: ST:0:0:{7b3eb750-0ca7-4a08-b0a7-b48c654b741c}&#x000D;&#x000A;Frame caption: &#x000D;&#x000A;Exception details:&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at DeveloperNews.FeedOrchestrator.&lt;CreateNewCombinedFeedAsync&gt;d__7.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at DeveloperNews.FeedOrchestrator.&lt;GetFeedsAsync&gt;d__5.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at DeveloperNews.FeedStore.&lt;GetFeedAsync&gt;d__6.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at DeveloperNews.DeveloperNewsPackage.&lt;InitializeToolWindowAsync&gt;d__7.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass31_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IVsAsyncToolWindowFactory-InitializeToolWindowAsync&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.VsTaskLibraryHelper.&lt;&gt;c__DisplayClass50_0.&lt;&lt;CancelWhenCancellationRequested&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.&lt;CreateToolWindowAsync&gt;d__145.MoveNext()</description>

**Comment by madskristensen** [comment] 2020-07-06 23:18
Please update to the latest build or download it here https://www.vsixgallery.com/extension/36cfa8d9-bd14-4d32-a8a6-34133aa2309d

**Comment by beihrle** [comment] 2020-07-06 23:34
Works now thanks! I have news tab now but no news but that's a different issue

**Comment by madskristensen** [comment] 2020-07-07 15:11
I believe it has to do with either failing to download or saving feeds to disk. I'm going to add some logging, so you can see what the error is and report that back to me, if you don't mind

**Comment by madskristensen** [comment] 2020-07-07 16:55
I've added error logging to the Output Window. Do you mind upgrading to the latest version and copy/paste the error message from the Output Window here?

**Comment by beihrle** [comment] 2020-07-07 20:07
I installed latest version and I don't see any news related output. 
There is no news option in the output window list. 
I do see unrelated errors for 'Learn the Shortcut'
7:54 AM: Debug.StartupProjects (no shortcut)
keeps repeating....

![image](https://user-images.githubusercontent.com/67930930/86836714-ffd4aa00-c0f1-11ea-9cb9-ebf32470883e.png)

**Comment by beihrle** [comment] 2020-07-07 20:12
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at DevNews.FeedDownloader.<DownloadFeedAsync>d__4.MoveNext()

**Comment by madskristensen** [comment] 2020-07-07 20:59
@beihrle I'm not sure I fixed the issue because I can't reproduce it locally. But I did add the .pdb files to the extension, so if you see the problem again, the callstack you get in the OutputWindow will be much more precise. Please check out the latest version and copy/paste the callstack if the issue isn't fixed. 

Thanks for helping test this!!

**Comment by beihrle** [comment] 2020-07-07 21:07
System.ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
   at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
   at System.DateTimeOffset..ctor(DateTime dateTime)
   at DevNews.FeedDownloader.<DownloadFeedAsync>d__4.MoveNext() in C:\projects\developernews\src\DeveloperNews\Feeds\FeedDownloader.cs:line 73

**Comment by madskristensen** [comment] 2020-07-07 21:29
Excellent. That did the trick. Turned out to be an issue with UTC timestamping. Should be fixed now in the latest version. You may have to delete `%temp%\Daily News` as well

**Comment by beihrle** [comment] 2020-07-07 21:34
Perfect, thanks!

![image](https://user-images.githubusercontent.com/67930930/86845830-2993ce00-c0fe-11ea-96bd-bc6db95aa0c5.png)

**Comment by madskristensen** [comment] 2020-07-07 21:37
Yes!!! Thank you so much

**Closed as completed by madskristensen** 2020-07-07 21:37 UTC
